services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3335:3335"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${LIMITED_DB_USERNAME}:${LIMITED_DB_PASSWORD}@db:5432/${POSTGRESQL_DATABASE}?schema=public
      PORT: ${PORT}
    networks:
      - api-network

  db:
    image: "bitnami/postgresql:latest"
    container_name: db
    user: root
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRESQL_POSTGRES_PASSWORD}
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
      LIMITED_DB_USERNAME: ${LIMITED_DB_USERNAME}
      LIMITED_DB_PASSWORD: ${LIMITED_DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - api-network
    volumes:
      - api-volume:/bitnami/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

networks:
  api-network:
    name: api-network

volumes:
  api-volume:
    name: api-volume