#!/bin/bash
set -e

# Cria um usuário de aplicação sem privilégios de DDL (não pode DROP/CREATE/ALTER, pois não é owner)
# Usa o superuser "postgres" pois "$POSTGRESQL_USERNAME" não tem o atributo CREATEROLE
export PGPASSWORD="${POSTGRESQL_POSTGRES_PASSWORD}"
psql -v ON_ERROR_STOP=1 --username postgres --dbname "$POSTGRESQL_DATABASE" <<-EOSQL
	CREATE USER ${LIMITED_DB_USERNAME} WITH PASSWORD '${LIMITED_DB_PASSWORD}';
	GRANT CONNECT ON DATABASE ${POSTGRESQL_DATABASE} TO ${LIMITED_DB_USERNAME};
	GRANT USAGE ON SCHEMA public TO ${LIMITED_DB_USERNAME};
	GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${LIMITED_DB_USERNAME};
	GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${LIMITED_DB_USERNAME};
	ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRESQL_USERNAME} IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${LIMITED_DB_USERNAME};
	ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRESQL_USERNAME} IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO ${LIMITED_DB_USERNAME};
EOSQL
